@url = http://localhost:5095/conferences-module

@hostId=edb73e3a-1543-44e4-ac0c-f12c49c298d5
@conferenceId=02a42ee8-a2aa-448d-9fe9-481e912ca83b

GET {{url}}

###
POST {{url}}/host
Content-Type: application/json

{
    "name":"host2",
    "description":"lorem ipsum"
}

###
GET {{url}}/host

###
GET {{url}}/host/{{hostId}}

###
PUT  {{url}}/host/{{hostId}}
Content-Type: application/json

{
    "name":"host#1-2",
    "description":"lorem ipsum2",
    "conferencesDtos":[]
}
###
DELETE {{url}}/host/{{hostId}}

######################


GET {{url}}/conference
###

POST {{url}}/conference
Content-Type: application/json

{
    "hostId":"{{hostId}}",
    "name":"Conferences#1",
    "description":"lorem ipsum",
    "location":"test 123",
    "from":"2023-05-01",
    "to":"2023-05-03",
    "participantLimit":100,
    "logoUrl":"null",
    "hostName":"test"
}

###
GET {{url}}/confereces

###
GET {{url}}/conference/{{conferenceId}}

###
PUT  {{url}}/conference/{{conferenceId}}
Content-Type: application/json

{
    "name":"conf#2"
}
